### ISSUE TITLE
Step 1 - just an opinion

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/this-sprite-needs-you#18]
Last Scratch example - I wasn't sure how the ‘Music Machine’ project fit in with the theme of the other example projects.

**Comment by libxx1** [comment]
Bit of stretch I guess. When you interact with it it grows the number of songs played, it's purpose is to play songs so it's gaining experience. If you don't interact with it it gets quieter until it's forgotten about. We wanted a machine example that was easy to do with the sprites we have in scratch.
