### ISSUE TITLE
Step 1, Line 85

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/this-sprite-needs-you#19]
This text isn’t on the staging site, but it does seem redundant, since we’ve already talked about the brief and shared the example projects. I’ve left it in for reference.

**Comment by libxx1** [comment]
It's not on the staging site because it's in a 'print only' tag. The bit in the 'no print' tag won't be printed out so they'll need that information again. 

I've updated it to repeat the information that's in the 'no print' tag as it's more useful to them on this occasion.

**Comment by megwangrpf** [comment]
Awesome. Just for my own understanding, we have some print/no print sections because we expect adults may print out the projects to use with classes/clubs/at home?

**Comment by libxx1** [comment]
Yep that's right. `Print only` doesn't appear on the screen, `no print` only appears on the screen and everything else appears in both places.....although the printed solution definitely needs work and doesn't handle everything as we want it to at the moment.
