### ISSUE TITLE
Step 2, Line 10. 

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/this-sprite-needs-you#20]
I wasn’t sure if the personal growth definition is linked to the idea that the learner is creating an ideal growth environment for their character, or that the learner will gain personal growth through this Scratch experience. I think it’s the former? If so, then maybe a definition of ‘Basic needs’ is more useful? Something like the following?

When basic needs like food and safety are met, we are creating the right conditions for creatures (including ourselves) to learn and grow. So the next time you’re feeling cranky or distracted, check your basic needs.

You guys are the experts. I just don’t like pointing out something and not offering a solution.

If we want to keep personal growth, then making some linking text before, about how we're creating a space for our character to have the right environment for growth?

**Comment by libxx1** [comment]
I like the basic needs example so have updated.
