### ISSUE TITLE
Step 3, Debug box

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/this-sprite-needs-you#21]
I wasn’t sure if the red code blocks were right for this audience, as I don’t know when making your own blocks is introduced. I expected the `say`block to be purple and the `if...then` to be orange with green in the middle.

**Comment by libxx1** [comment]
You're absolutely right, it has nothing to do with making their own blocks and everything to do with us not putting the right brackets in :) Updated now to be this ..... 

say (name) for (2) seconds
say [name] for (2) seconds
<(health) > (0)> // means the health variable must be bigger than 0
<(health) < (5)> // means the health variable must be smaller than 5
